server:
  port: 9293
spring:
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  # profiles:
  #  active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/api-nubank-desafio #${SPRING_DATASOURCE_URL}
    username: postgres #${SPRING_DATASOURCE_USERNAME}
    password: postgres #${SPRING_DATASOURCE_PASSWORD}
jpa:
  open-in-view: true
  hibernate:
    ddl-auto: update
    show-sql: true
    format-sql: true
flyway:
  create-schemas: true
  enabled: true
  locations:
    classpath: db/migration
  baseline-on-migrate: true
spring-doc:
  pathsToMatch:
    - /**
swagger-ui:
  user-root-path: true